import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'ReSearch of AI Text BooK',
      items: [
        {
          type: 'category',
          label: 'Chapter 1: Introduction to Physical AI',
          items: [
            'physical-ai-book/intro/foundations',
            'physical-ai-book/intro/digital-to-embodied',
            'physical-ai-book/intro/humanoid-landscape',
            'physical-ai-book/intro/sensor-systems',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 2: ROS 2 Fundamentals',
          items: [
            {
              type: 'autogenerated',
              dirName: 'physical-ai-book/chapter2',
            },
          ],
        },
        {
          type: 'category',
          label: 'Chapter 3: Robot Simulation with Gazebo',
          items: [
            {
              type: 'autogenerated',
              dirName: 'physical-ai-book/chapter3',
            },
          ],
        },
        {
          type: 'category',
          label: 'Chapter 4: NVIDIA Isaac Platform',
          items: [
            {
              type: 'autogenerated',
              dirName: 'physical-ai-book/chapter4',
            },
          ],
        },
        {
          type: 'category',
          label: 'Chapter 5: Humanoid Robot Development',
          items: [
            {
              type: 'autogenerated',
              dirName: 'physical-ai-book/chapter5',
            },
          ],
        },
        {
          type: 'category',
          label: 'Chapter 6: Conversational Robotics',
          items: [
            {
              type: 'autogenerated',
              dirName: 'physical-ai-book/chapter6',
            },
          ],
        },
      ],
    },
  ],
   
};

export default sidebars;
